Add Mac OS aarch64
[new][skip-win][skip-win22][skip-win19][skip-win15][skip-osx][skip-linux][skip-linux64]

diff --git a/.github/workflows/edopro.yml b/.github/workflows/edopro.yml
--- a/.github/workflows/edopro.yml
+++ b/.github/workflows/edopro.yml
@@ -459,6 +459,118 @@ jobs:
         asset_name: installed_x64-osx.7z
         asset_content_type: application/x-7z-compressed
 
+  aarch64-osx:
+    runs-on: macos-latest
+    needs: create-release
+    if: contains(github.event.head_commit.message, '[skip-osx64]') != true
+    env:
+      MACOSX_DEPLOYMENT_TARGET: 11.0
+    steps:
+    - uses: actions/checkout@v1
+      with:
+        fetch-depth: 1
+    - name: Download 1-latest release's json
+      shell: bash
+      if: (startsWith(github.ref, 'refs/tags/') && contains(github.event.head_commit.message, '[new]') != true)
+      run: |
+        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -o tmp.json https://api.github.com/repos/edo9300/edopro-vcpkg-cache/releases
+        echo "$(node -e "console.log(JSON.stringify(JSON.parse(require('fs').readFileSync('./tmp.json'))[1]))")" >> previous.json
+        rm -f tmp.json
+    - name: Download latest release's json
+      shell: bash
+      if: (startsWith(github.ref, 'refs/tags/') != true && contains(github.event.head_commit.message, '[new]') != true)
+      run: |
+        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -o previous.json https://api.github.com/repos/edo9300/edopro-vcpkg-cache/releases/latest
+    - name: Download cached archive
+      shell: bash
+      if: contains(github.event.head_commit.message, '[new]') != true
+      run: |
+        curl -O -J -L -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/octet-stream" "$(node -e "JSON.parse(require('fs').readFileSync('./previous.json'))['assets'].forEach(function(obj){if(obj['name']=='installed_x64-osx.7z'){ console.log(obj['url']) }})")"
+    # - name: Install 10.11 SDK
+      # run: |
+        # curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name \
+          # https://raw.githubusercontent.com/edo9300/ygopro/master/travis/get-osx-sdk.sh
+        # chmod +x get-osx-sdk.sh
+        # ./get-osx-sdk.sh $MACOSX_DEPLOYMENT_TARGET
+    #needed to build mpg123
+    # - name: Install Homebrew prerequisites
+      # if: contains(github.event.head_commit.message, '[skip-osx]') != true
+      # run: |
+        # brew install yasm
+    - name: Extract vcpkg cache
+      if: contains(github.event.head_commit.message, '[new]') != true
+      run: |
+        dir=$PWD
+        cd $VCPKG_INSTALLATION_ROOT
+        7z x $dir/installed_aarch64-osx.7z -aos
+        cd $dir
+        rm -f installed_aarch64-osx.7z
+    - name: Upgrade vcpkg dependencies
+      if: contains(github.event.head_commit.message, '[skip-osx]') != true
+      run: |
+        vcpkg upgrade --overlay-ports=ports --no-dry-run --triplet=arm64-osx
+    # - name: Build patched Irrlicht
+      # if: (contains(github.event.head_commit.message, '[do-irr]') || contains(github.event.head_commit.message, '[new]'))
+      # run: |
+        # curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name \
+          # https://github.com/edo9300/irrlicht1-8-4/archive/master.zip
+        # 7z x irrlicht1-8-4-master.zip
+        # cd irrlicht1-8-4-master
+        # xcodebuild -project source/Irrlicht/MacOSX/MacOSX.xcodeproj -configuration Release -target libIrrlicht.a SYMROOT=build -sdk $SDKROOT -parallelizeTargets
+        # rm -r -f $VCPKG_INSTALLATION_ROOT/irrlicht
+        # mkdir -p ../irrlicht/lib
+        # cp -r include ../irrlicht/include
+    - name: Build patched Irrlicht 1.9
+      if: (contains(github.event.head_commit.message, '[do-irr]') || contains(github.event.head_commit.message, '[new]'))
+      env:
+        SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
+      run: |
+        curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name \
+          https://github.com/edo9300/irrlicht1-8-4/archive/1.9-custom.zip
+        7z x irrlicht1-8-4-1.9-custom.zip
+        cd irrlicht1-8-4-1.9-custom
+        xcodebuild ARCHS=arm64 ONLY_ACTIVE_ARCH=NO SYSTEM_HEADER_SEARCH_PATHS=./../../include -project source/Irrlicht/Irrlicht.xcodeproj -configuration Release -target Irrlicht_OSX SYMROOT=build -sdk $SDKROOT -parallelizeTargets
+        rm -r -f $VCPKG_INSTALLATION_ROOT/irrlicht
+        mkdir -p ../irrlicht/lib
+        cp -r include ../irrlicht/include
+        cp source/Irrlicht/build/Release/libIrrlicht.a ../irrlicht/lib
+    # - name: Install SDL2 from vcpkg 
+      # env:
+        # SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
+      # run: |
+        # vcpkg install sdl2
+    - name: Install vcpkg dependencies
+      run: |
+        vcpkg install --overlay-ports=ports \
+          libevent openssl libgit2 \
+          openal-soft \
+          libflac libvorbis \
+          fmt nlohmann-json \
+          discord-rpc-payload \
+          --triplet=arm64-osx
+    - name: 7-Zip binaries
+      run: |
+        mv irrlicht $VCPKG_INSTALLATION_ROOT || true
+        cd $VCPKG_INSTALLATION_ROOT
+        7z a installed_aarch64-osx.7z installed scripts .vcpkg-root irrlicht
+    - name: Get upload endpoint
+      id: get_endpoint
+      if: startsWith(github.ref, 'refs/tags/')
+      run: |
+        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -o latest.json https://api.github.com/repos/edo9300/edopro-vcpkg-cache/releases/latest
+        echo ::set-output name=upload_url::$(node -e "console.log(JSON.parse(require('fs').readFileSync('./latest.json'))['upload_url'])")
+        echo ::set-output name=asset_path::$VCPKG_INSTALLATION_ROOT/installed_aarch64-osx.7z
+    - name: Upload binaries to GitHub
+      if: startsWith(github.ref, 'refs/tags/')
+      uses: actions/upload-release-asset@v1.0.1
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      with:
+        upload_url: ${{ steps.get_endpoint.outputs.upload_url }}
+        asset_path: ${{ steps.get_endpoint.outputs.asset_path }}
+        asset_name: installed_aarch64-osx.7z
+        asset_content_type: application/x-7z-compressed
+
   x64-linux:
     runs-on: ubuntu-18.04
     needs: create-release
@@ -603,6 +715,7 @@ jobs:
         || contains(github.event.head_commit.message, '[skip-win19]')
         || contains(github.event.head_commit.message, '[skip-win22]')
         || contains(github.event.head_commit.message, '[skip-osx]')
+        || contains(github.event.head_commit.message, '[skip-osx64]')
         || contains(github.event.head_commit.message, '[skip-linux]')
         || contains(github.event.head_commit.message, '[skip-linux64]'))
         && startsWith(github.ref, 'refs/tags/'))
@@ -634,7 +747,7 @@ jobs:
     - name: Download cached archive linux64
       if: contains(github.event.head_commit.message, '[skip-linux64]')
       run: |
-        curl -O -J -L -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/octet-stream" "$(node -e "JSON.parse(require('fs').readFileSync('./previous.json'))['assets'].forEach(function(obj){if(obj['name']=='installed_x64-linux.7z'){ console.log(obj['url']) }})")"
+        curl -O -J -L -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/octet-stream" "$(node -e "JSON.parse(require('fs').readFileSync('./previous.json'))['assets'].forEach(function(obj){if(obj['name']=='installed_aarch64-linux.7z'){ console.log(obj['url']) }})")"
     - name: Upload binaries to GitHub linux64
       if: contains(github.event.head_commit.message, '[skip-linux64]')
       uses: actions/upload-release-asset@v1.0.1
@@ -658,6 +771,20 @@ jobs:
         upload_url: ${{ steps.get_endpoint.outputs.upload_url }}
         asset_path: ./installed_x64-osx.7z
         asset_name: installed_x64-osx.7z
+        asset_content_type: application/zip
+    - name: Download cached archive osx64
+      if: contains(github.event.head_commit.message, '[skip-osx64]')
+      run: |
+        curl -O -J -L -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/octet-stream" "$(node -e "JSON.parse(require('fs').readFileSync('./previous.json'))['assets'].forEach(function(obj){if(obj['name']=='installed_aarch64-osx.7z'){ console.log(obj['url']) }})")"
+    - name: Upload binaries to GitHub osx64
+      if: contains(github.event.head_commit.message, '[skip-osx64]')
+      uses: actions/upload-release-asset@v1.0.1
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      with:
+        upload_url: ${{ steps.get_endpoint.outputs.upload_url }}
+        asset_path: ./installed_aarch64-osx.7z
+        asset_name: installed_aarch64-osx.7z
         asset_content_type: application/zip
     - name: Download cached archive vs2015
       if: contains(github.event.head_commit.message, '[skip-win15]')
